# Generated by Django 4.1.7 on 2023-04-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeinformation',
            name='name',
            field=models.CharField(default='no name', max_length=256),
        ),
        migrations.AlterField(
            model_name='contract',
            name='administrative_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_contract.administrativeinformation'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='coverage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_contract.coverage'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expenses',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_contract.expenses'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='premium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_contract.premium'),
        ),
    ]
