# Generated by Django 4.1.7 on 2023-04-25 11:38

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_contract', '0002_administrativeinformation_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_company_name'),
        ),
    ]
