# Generated by Django 4.2 on 2023-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_contract', '0002_company_email_alter_excessofloss_reinstatements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excessofloss',
            name='reinstatements',
        ),
        migrations.AddField(
            model_name='excessofloss',
            name='reinstatements_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='aggregate_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='aggregate_retention',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='event_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='event_retention',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='risk_limit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='excessofloss',
            name='risk_retention',
            field=models.FloatField(default=None, null=True),
        ),
    ]
