# Generated by Django 4.2.1 on 2023-05-04 12:21

import analysis.models.Code
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabetic_code', models.CharField(max_length=3)),
                ('numeric_code', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('alphabetic_code', 'numeric_code')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code_3', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\w{3}$', 'Must be exactly 3 characters')])),
                ('name', models.CharField(default='no_name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.FloatField(help_text='percentage share acquired')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code_3', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\w{3}$', 'Must be exactly 3 characters')])),
                ('name', models.CharField(default='no_name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfront_brokerage', models.FloatField()),
                ('upfront_commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExposureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.OneToOneField(default=analysis.models.Code.Code.next_analysis_code, on_delete=django.db.models.deletion.PROTECT, to='analysis.code')),
            ],
        ),
        migrations.CreateModel(
            name='InflationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfront_premium', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcessOfLoss',
            fields=[
                ('coverage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.coverage')),
                ('risk_retention', models.FloatField(default=None, null=True)),
                ('risk_limit', models.FloatField(default=None, null=True)),
                ('event_retention', models.FloatField(default=None, null=True)),
                ('event_limit', models.FloatField(default=None, null=True)),
                ('aggregate_retention', models.FloatField(default=None, null=True)),
                ('aggregate_limit', models.FloatField(default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analysis.coverage',),
        ),
        migrations.CreateModel(
            name='QuotaShare',
            fields=[
                ('coverage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analysis.coverage')),
                ('share', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analysis.coverage',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('code', models.OneToOneField(default=analysis.models.Code.Code.next_program_code, on_delete=django.db.models.deletion.PROTECT, to='analysis.code')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.currency')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.company')),
            ],
        ),
        migrations.CreateModel(
            name='LossDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_total_distribution', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('gamma', 'gamma'), ('pareto', 'pareto'), ('ecdf', 'ecdf')], default='gamma', max_length=16)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.exposureanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='exposureanalysis',
            name='inflation_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.inflationpattern'),
        ),
        migrations.AddField(
            model_name='exposureanalysis',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.program'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.OneToOneField(default=analysis.models.Code.Code.next_contract_code, on_delete=django.db.models.deletion.PROTECT, to='analysis.code')),
                ('coverage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='analysis.coverage')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.currency')),
                ('expenses', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='analysis.expenses')),
                ('premium', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='analysis.premium')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.program')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.country'),
        ),
        migrations.CreateModel(
            name='Reinstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveIntegerField()),
                ('size', models.FloatField(default=1)),
                ('cost', models.FloatField(default=1)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.coverage')),
            ],
            options={
                'unique_together': {('coverage', 'nr')},
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_company_name'),
        ),
    ]
