# Generated by Django 4.1.7 on 2023-04-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InflationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(verbose_name='values')),
            ],
        ),
        migrations.CreateModel(
            name='ExposureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('loss_distributions', models.JSONField()),
                ('inflation_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.inflationpattern')),
            ],
        ),
    ]
