# Generated by Django 4.1.7 on 2023-04-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_contract', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposureanalysis',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_contract.program'),
        ),
    ]
