# Generated by Django 4.1.7 on 2023-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflationpattern',
            name='values',
            field=models.JSONField(),
        ),
    ]
