# Generated by Django 4.2 on 2023-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_inflationpattern_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposureanalysis',
            name='loss_distributions',
        ),
        migrations.AddField(
            model_name='exposureanalysis',
            name='loss_distributions_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='inflationpattern',
            name='values',
            field=models.JSONField(default=dict),
        ),
    ]
